// anserini/src/main/frontend/pages/_app.tsx
/*
 *   Copyright 2025 Kompile Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * Anserini: A Lucene toolkit for reproducible information retrieval research
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import '../styles/globals.css';
import type { AppProps } from 'next/app';
import { ChakraProvider } from '@chakra-ui/react';

function MyApp({ Component, pageProps } : AppProps) {
  return (
    <ChakraProvider>
      <Component {...pageProps} />
    </ChakraProvider>
  );
}

export default MyApp;

// kompile-app/kompile-app-main/src/main/frontend/src/app/app.component.ts
/*
 *  Copyright 2025 Kompile Inc.
 *  *
 *  * Licensed under the Apache License, Version 2.0 (the "License");
 *  * you may not use this file except in compliance with the License.
 *  * You may obtain a copy of the License at
 *  *
 *  * http://www.apache.org/licenses/LICENSE-2.0
 *  *
 *  * Unless required by applicable law or agreed to in writing, software
 *  * distributed under the License is distributed on an "AS IS" BASIS,
 *  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  * See the License for the specific language governing permissions and
 *  * limitations under the License.
 */

import { Component } from '@angular/core';

@Component({
  standalone: false,
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'RAG MCP Anserini Console';
  activeTab: 'chat' | 'documents' | 'mcpTools' = 'chat'; // Default tab
}

<!--
  ~ * Copyright 2025 Kompile Inc.
  ~  *
  ~  * Licensed under the Apache License, Version 2.0 (the "License");
  ~  * you may not use this file except in compliance with the License.
  ~  * You may obtain a copy of the License at
  ~  *
  ~  * http://www.apache.org/licenses/LICENSE-2.0
  ~  *
  ~  * Unless required by applicable law or agreed to in writing, software
  ~  * distributed under the License is distributed on an "AS IS" BASIS,
  ~  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~  * See the License for the specific language governing permissions and
  ~  * limitations under the License.
  -->

<div class="app-container">
  <header>
    <h1>RAG MCP Anserini Console</h1>
  </header>

  <nav>
    <button (click)="activeTab = 'chat'" [class.active]="activeTab === 'chat'">Chat</button>
    <button (click)="activeTab = 'documents'" [class.active]="activeTab === 'documents'">Document Management</button>
    <button (click)="activeTab = 'mcpTools'" [class.active]="activeTab === 'mcpTools'">View MCP Tools</button>
  </nav>

  <main>
    <div *ngIf="activeTab === 'chat'">
      <app-chat-interface></app-chat-interface>
    </div>
    <div *ngIf="activeTab === 'documents'">
      <app-document-manager></app-document-manager>
    </div>
    <div *ngIf="activeTab === 'mcpTools'">
      <app-mcp-tools-viewer></app-mcp-tools-viewer>
    </div>
  </main>

  <footer>
    <p>RAG MCP Anserini Starter Frontend</p>
  </footer>
</div>
